version: '2.3'

services:
  ros2dev:
    image: ${IMAGE}
    runtime: nvidia
    network_mode: host
    privileged: true
    user: "${UID_HOST}:${GID_HOST}"
    working_dir: /ros_ws
    environment:
      - ROS_WORKSPACE=/ros_ws
    volumes:
      - ${ROS_WS}:/ros_ws
      - ${ROS_SETUP}:/ros_setup
      - /dev:/dev
      - /sys:/sys
    devices:
      - /dev/ttyTHS1:/dev/ttyTHS1
    tty: true
    stdin_open: true
    command: ["/bin/bash"]

  ros2run:
    image: ${IMAGE}
    runtime: nvidia
    network_mode: host
    privileged: true
    user: "${UID_HOST}:${GID_HOST}"
    working_dir: /ros_ws
    environment:
      - ROS_WORKSPACE=/ros_ws
    volumes:
      - ${ROS_WS}:/ros_ws
      - ${ROS_SETUP}:/ros_setup
      - /dev:/dev
      - /sys:/sys
    devices:
      - /dev/ttyTHS1:/dev/ttyTHS1
    tty: true
    stdin_open: true
    command: ["/bin/bash"]
